import os
import discord
import random
from main import bot
from GeneralCommands import JoinChannel, PlayAudioFile
from MusicPlayer import music_play_session


class Ido_Soundboard_Button(discord.ui.Button):
    def __init__(self, name):
        self.sound_name = name.split('.')[0]
        self.file_name = str(name)
        super().__init__(label=self.sound_name, style=discord.ButtonStyle.blurple)

    async def callback(self, interaction: discord.Interaction):
        if music_play_session:
            await interaction.response.send_message("Cannot play ido, there is an active music session.",
                                                    ephemeral=True)
            return
        channel = interaction.user.voice.channel
        voice_client = await JoinChannel(channel_to_join=channel, interaction=interaction, respond=False)
        # try:
        #     channel = interaction.user.voice.channel
        #     voice_client = await channel.connect()
        # except:
        #     voice_client = interaction.client.voice_clients[0]
        file_path = r"C:\Users\Roy\Downloads\idos\\" + self.file_name
        audio_source = discord.FFmpegPCMAudio(file_path)
        voice_client.play(audio_source)
        await interaction.response.send_message(f"Playing {self.sound_name}", ephemeral=True)


@bot.tree.command(name="ido", description="Ido's SoundBoard")
async def ido(interaction: discord.Interaction):
    ido_soundboard = discord.ui.View(timeout=180)
    ido_soundboard.interaction = interaction

    async def timeout():
        for button in ido_soundboard.children:
            button.disabled = True
        await interaction.edit_original_response(view=ido_soundboard)
    ido_soundboard.on_timeout = timeout

    for sound in os.listdir(r'C:\Users\Roy\Downloads\idos'):
        ido_soundboard.add_item(Ido_Soundboard_Button(name=sound))
    embed = discord.Embed(
        title="Ido's Soundboard <:ChadIdo12:903964570912186378> <:ChadIdo13:903964570979287053>",
        description='A lot of sounds generated by Ido',
        color=0x8b913c,
    )
    embed.set_thumbnail(
        url='https://cdn.discordapp.com/attachments/1037365897897185280/1065015322517712956/IMG_20230113_132602.jpg')
    await interaction.response.send_message(embed=embed, view=ido_soundboard)


@bot.tree.command(name="askido", description="Random Ido response")
async def askido(interaction: discord.Interaction):
    if music_play_session:
        await interaction.response.send_message("Cannot play ido, there is an active music session.", ephemeral=True)
        return
    await interaction.response.defer()
    try:
        channel = interaction.user.voice.channel
    except:
        await interaction.followup.send(f"You need to be at a voice channel on a server I'm in.", ephemeral=True)
        return
    voice_client = await JoinChannel(interaction, channel_to_join=channel, respond=False)

    auido_list = os.listdir(r"C:\Users\Roy\Downloads\idos")
    rand_audio = random.choice(auido_list)
    file_path = r"C:\Users\Roy\Downloads\idos\\" + rand_audio
    await PlayAudioFile(voice_client, file_path, volume=None)

    await interaction.followup.send(f"Playing {rand_audio.split('.')[0]}", ephemeral=False)
